path: default
title: Home
icon: mdi:home
badges: []
cards:
  - title: Основная панель
    show_header_toggle: false
    type: entities
    entities:
      - switch.sw_main
      - switch.sw_main_timers
      # - sensor.temp_out
      # - sensor.temp_in
      # - sensor.temp_x
      - sensor.temp1_sauna
      - sensor.temp2_sauna
      - light.floodlight
      - light.hall
  - title: Security
    type: entities
    show_header_toggle: false
    entities:
      - input_boolean.enable_alarm
      - automation.alarm_motion_at_home
      - input_boolean.alarming
      - sensor.hall_pir_last_changed
      - binary_sensor.ups_online_status
      - binary_sensor.ewelink_ms01_80d3901f_ias_zone
  - title: СемьЯ
    type: entities
    show_header_toggle: false
    entities:
      - person.vladislav
      - person.eva
  - title: Automation
    type: entities
    entities:
      - automation.notification_sauna_heating
      - automation.notification_hdd_use_alarm
      - automation.notification_early_frosts
      - automation.notification_of_main_switches
      - automation.pir_persistent_notification
      - automation.alarm_low_temperature_at_home
      - automation.notification_ups_online
  - title: Lights
    type: entities
    entities:
      - light.father
      - light.mather
      - light.hall
      - light.toilet
      - light.floodlight
      - light.sauna

