- platform: mqtt
  name: "sonoff_95B510 LWT"
  state_topic: "tele/sonoff_95B510/LWT"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity

- platform: mqtt
  name: "sonoff_F4BC40 LWT"
  state_topic: "tele/sonoff_F4BC40/LWT"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity
 
