title: Cottage61 
views:
  - path: default
    title: Home
    icon: mdi:home
    badges: []
    cards:
      - title: Основной выключатель
        show_header_toggle: true
        type: entities
        entities:
          - switch.sonoff_mainswitch
          - sensor.mqtt_net_datetime_control
          - sensor.temp_out
          - sensor.temp_in
          - sensor.temp_x
          - switch.sonoff_mainswitch_timers
      - title: Security
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.enable_alarm
          - automation.alarm_motion_at_home
          - input_boolean.alarming
          - sensor.hall_pir_last_changed
      - title: СемьЯ
        type: entities
        show_header_toggle: false
        entities:
          - device_tracker.vlad_nexus
      - title: Automation
        type: entities
        entities:
          - automation.automatic_winter_heating_the_water_pipe
          - automation.notification_sauna_heating
          - automation.disk_use_alarm
          - automation.notification_early_frosts
          - automation.notification_of_main_switches
          - automation.pir_persistent_notification
          - automation.alarm_low_temperature_at_home
  - path: devices
    title: Devices
    icon: 'mdi:chip'
    badges: []
    cards:
      - title: Основной выключатель
        show_header_toggle: true
        type: entities
        entities:
          - switch.sonoff_mainswitch
          - sensor.mqtt_net_datetime_control
          - sensor.temp_out
          - sensor.temp_in
          - sensor.temp_x
          - switch.sonoff_mainswitch_timers
      - title: Движение/Присутствие
        show_header_toggle: false
        type: entities
        entities:
          - sensor.hall_pir_last_changed
          - binary_sensor.hall_pir
      - entities:
          - switch.sonoff_801e75_ch1
          - switch.sonoff_801e75_ch2
          - switch.sonoff_801e75_ch3
          - switch.sonoff_801e75_ch4
          - switch.sonoff_801e75_timers
        show_header_toggle: true
        title: Свет/Выключатели
        type: entities
      - entities:
          - switch.sonoff_sauna
          - sensor.temp1_sauna
          - sensor.temp2_sauna
          - switch.sonoff_sauna_timers
        show_header_toggle: true
        title: Сауна
        type: entities
      - entities:
          - switch.tasmota_floodlight
          - switch.tasmota_floodlight_timers
        show_header_toggle: true
        title: Улица
        type: entities
      - entities:
          - switch.sonoff_water
          - sensor.temp_water
          - switch.sonoff_water_timers
        show_header_toggle: true
        title: Подогрев трубы
        type: entities
      - entities:
          - switch.sonoff_pow
          - sensor.sonoff_pow_voltage
          - sensor.sonoff_pow_power
          - sensor.sonoff_pow_today
          - sensor.sonoff_pow_total
          - switch.sonoff_pow_timers
        show_header_toggle: true
        title: Розетка-счетчик
        type: entities
      - entities:
          - sensor.sonoff_bridge_433
          - sensor.sonoff_b2df94_wifi
          - sensor.sonoff_b2df94_uptime
        show_header_toggle: true
        title: Шлюз RF433
        type: entities
      - entities:
          - switch.sonoff_plug
          - switch.sonoff_plug_timers
        show_header_toggle: true
        title: Умная розетка
        type: entities
  - path: net
    title: Net
    icon: 'mdi:switch'
    badges: []
    cards:
      - title: NMap
        type: entities
        entities:
          - device_tracker.sonoff_95b510
          - device_tracker.sonoff_26575d
          - device_tracker.sonoff_f4bc40
          - device_tracker.sonoff_801e75
          - device_tracker.sonoff_b2df94
          - device_tracker.sonoff_68b5c7
          - device_tracker.sonoff_68ac8d
  - path: weather
    title: Weather
    icon: 'mdi:weather-cloudy'
    badges: []
    cards:
      - title: Сегодня
        type: entities
        entities:
          - sun.sun
          - sensor.temp_out
          - sensor.temp_in
      - entity: camera.weather_radar_temp
        type: picture-entity
      - entity: camera.weather_radar_wind
        type: picture-entity
      - entity: camera.weather_radar_press
        type: picture-entity
      - entity: camera.weather_radar_apcp
        type: picture-entity
      - title: Weather YR
        type: entities
        entities:
          - sensor.weather_yr_symbol
          - sensor.weather_yr_temperature
          - sensor.weather_yr_pressure
          - sensor.weather_yr_humidity
          - sensor.weather_yr_wind_speed
          - sensor.weather_yr_wind_direction
  - path: sys
    title: Development
    icon: 'mdi:clippy'
    badges: []
    cards:
      - title: ПЭВМ
        type: entities
        entities:
          - sensor.last_boot
          - sensor.disk_use_percent_home
          - sensor.disk_use_percent_root
          - sensor.memory_use_percent
          - sensor.date
          - sensor.time
      - title: Script
        show_header_toggle: false
        type: entities
        entities:
          - script.notify_ping_me
          - script.sonoff_qry_states
      - title: Sonoff/Tasmota workplace
        type: entities
        entities:
          - script.sonoff_qry_states
          - binary_sensor.sonoff_95b510_lwt
          - binary_sensor.sonoff_26575d_lwt
          - binary_sensor.sonoff_f4bc40_lwt
          - binary_sensor.sonoff_801e75_lwt
          - binary_sensor.sonoff_b2df94_lwt
          - binary_sensor.sonoff_68b5c7_lwt
          - binary_sensor.sonoff_68ac8d_lwt
          - binary_sensor.tasmota_ab76c3_lwt
