title: Cottage61 
views:
  - !include lovelace/sys.yaml
  - !include lovelace/default.yaml
  - !include lovelace/devices.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/network.yaml
  - path: test
    title: Test
    icon: 'mdi:bug'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - timer.looper_timer
              - timer.period_timer
  - path: links
    title: Ресурсы
    icon: 'mdi:lan'
    badges: []
    cards:
      - !include lovelace/_links.yaml
  
