homeassistant:

  customize_glob:
    "input_select.log_*":
      icon: mdi:bug
      hidden: False
    "sensor.sonoff_*_wifi":
      icon: mdi:wifi
    "sensor.sonoff_*_uptime":
      icon: mdi:timelapse

  customize:
    group.motion_detection:
      friendly_name: 'Движение/Присутствие'
    switch.sonoff_801e75_ch1:
      friendly_name: 'Туалет'
      icon: mdi:lamp
    switch.sonoff_801e75_ch2:
      friendly_name: 'Мама'
      icon: mdi:lamp
    switch.sonoff_801e75_ch3:
      friendly_name: 'Папа'
      icon: mdi:white-balance-incandescent
    switch.sonoff_801e75_ch4:
      friendly_name: 'Зал'
      icon: mdi:white-balance-iridescent
    switch.sonoff_801e75_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_4pro:
      friendly_name: 'Свет/Выключатели'
    sensor.sonoff_bridge_433:
      friendly_name: 'Last cod'
    group.sonoff_bridge:
      friendly_name: 'Шлюз RF433'
    switch.sonoff_mainswitch:
      icon: mdi:power
      friendly_name: 'Рубильник'
    sensor.mqtt_net_datetime_control:
      friendly_name: 'Временная метка'
    sensor.temp_out:
      friendly_name: 'Температура снаружи'
    sensor.temp_in:
      friendly_name: 'Температура внутри'
    sensor.temp_x:
      friendly_name: 'Температура в углу'
    switch.sonoff_mainswitch_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
      assumed_state: false
    group.sonoff_mainswitch:
      friendly_name: 'Основной выключатель'
    switch.sonoff_pow:
      icon: mdi:power-plug
      friendly_name: 'Розетки'
    sensor.sonoff_pow_power:
      icon: mdi:scale
      friendly_name: 'Мощьность'
    sensor.sonoff_pow_voltage:
      friendly_name: 'Напряжение'
      icon: mdi:flash-circle
    sensor.sonoff_pow_today:
      icon: mdi:chart-timeline
      friendly_name: 'Сегодня'
    sensor.sonoff_pow_total:
      icon: mdi:counter
      friendly_name: 'Всего'
    switch.sonoff_pow_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_pow:
      friendly_name: 'Розетка-счетчик'
    switch.sonoff_plug:
      icon: mdi:power-plug
      friendly_name: 'Розетка'
    switch.sonoff_plug_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_plug:
      friendly_name: 'Умная розетка'
    switch.sonoff_sauna:
      icon: mdi:power-plug
      friendly_name: 'Лампа сауна'
    sensor.temp1_sauna:
      friendly_name: 'Температура №1'
      icon: mdi:oil-temperature
    sensor.temp2_sauna:
      friendly_name: 'Температура №2'
      icon: mdi:oil-temperature
    switch.sonoff_sauna_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_sauna:
      friendly_name: 'Сауна'
    switch.sonoff_water:
      icon: mdi:power-plug
      friendly_name: 'Эл.кабель'
    sensor.temp_water:
      friendly_name: 'Температура трубы'
      icon: mdi:oil-temperature
    switch.sonoff_water_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_water:
      friendly_name: 'Подогрев трубы'
    switch.tasmota_floodlight:
      icon: mdi:power-plug
      friendly_name: 'Прожектор'
    switch.tasmota_floodlight_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.tasmota_floodlight:
      friendly_name: 'Улица'
  #--------------------------------------------

  today:
    entities:
      - sun.sun
      - sensor.temp_out
      - sensor.temp_in
      
       


  #debug:
  #  entities:
  #    - input_select.log_level

      

      
      
      

