#sonoff-pow -------------------------------------
switch:
  - platform: mqtt
    name: "sw_plug"
    state_topic: "stat/sw_plug/POWER"
    command_topic: "cmnd/sw_plug/POWER"
    availability_topic: "tele/sw_plug/LWT"
#    json_attributes_topic: "tele/sw_plug/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
#    retain: false
  - platform: mqtt
    name: "sw_plug_timers"
    state_topic: "stat/sw_plug/RESULT"
    command_topic: "cmnd/sw_plug/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sw_plug/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "sw_plug today"
    state_topic: "tele/sw_plug/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sw_plug total"
    state_topic: "tele/sw_plug/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sw_plug power"
    state_topic: "tele/sw_plug/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "sw_plug voltage"
    state_topic: "tele/sw_plug/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"

binary_sensor:
  - platform: mqtt
    name: "sw_plug LWT"
    state_topic: "tele/sw_plug/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sw_plug/STATE"


