
#sonof-pow -------------------------------------
- platform: mqtt
  name: "sonoff_26575D"
  state_topic: "stat/sonoff_26575D/POWER"
  command_topic: "cmnd/sonoff_26575D/POWER"
  availability_topic: "tele/sonoff_26575D/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not-available: "Offline"
  optimistic: false
  #retain: false

#sonof-mainswitch -------------------------------------
- platform: mqtt
  name: "sonoff_95B510"
  state_topic: "stat/sonoff_95B510/POWER"
  command_topic: "cmnd/sonoff_95B510/POWER"
  availability_topic: "tele/sonoff_95B510/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not-available: "Offline"
  optimistic: false
  #retain: false


#sonof-water -------------------------------------
- platform: mqtt
  name: "sonoff_F4BC40"
  state_topic: "stat/sonoff_F4BC40/POWER"
  command_topic: "cmnd/sonoff_F4BC40/POWER"
  availability_topic: "tele/sonoff_F4BC40/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not-available: "Offline"
  optimistic: false
  #retain: false
