###################################################
## Various MQTT sensors
###################################################

#sonoff-pow----------------------------------------
- platform: mqtt
  name: "sonoff_26575D energy"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff_26575D power"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: "sonoff_26575D voltage"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "V"
- platform: mqtt
  name: "sonoff_26575D wifi"
  state_topic: "tele/sonoff_26575D/STATE"
  value_template: "{{ value_json.Wifi.RSSI }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "sonoff_26575D uptime"
  state_topic: "tele/sonoff_26575D/STATE"
  value_template: "{{ value_json.Uptime }}"
  unit_of_measurement: ""

