###################################################
## Various MQTT sensors
###################################################

#sonoff-pow----------------------------------------
- platform: mqtt
  name: "sonoff 26575D today"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Today }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff 26575D total"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Total }}"
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff 26575D power"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "W"
- platform: mqtt
  name: "sonoff 26575D voltage"
  state_topic: "tele/sonoff_26575D/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "V"
- platform: mqtt
  name: "sonoff 26575D wifi"
  state_topic: "tele/sonoff_26575D/STATE"
  value_template: "{{ value_json.Wifi.RSSI }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "sonoff 26575D uptime"
  state_topic: "tele/sonoff_26575D/STATE"
  value_template: "{{ value_json.Uptime }}"
  unit_of_measurement: ""
#sonoff-base-1----------------------------------------
- platform: mqtt
  name: "sonoff F4BC40 wifi"
  state_topic: "tele/sonoff_F4BC40/STATE"
  value_template: "{{ value_json.Wifi.RSSI }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "sonoff F4BC40 uptime"
  state_topic: "tele/sonoff_F4BC40/STATE"
  value_template: "{{ value_json.Uptime }}"
  unit_of_measurement: ""
#sonoff-mainswitch----------------------------------------
- platform: mqtt
  name: "sonoff 95B510 wifi"
  state_topic: "tele/sonoff_95B510/STATE"
  value_template: "{{ value_json.Wifi.RSSI }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "sonoff 95B510 uptime"
  state_topic: "tele/sonoff_95B510/STATE"
  value_template: "{{ value_json.Uptime }}"
  unit_of_measurement: ""


