###################################################
## Various MQTT sensors
###################################################

#sonoff-base-1----------------------------------------
- platform: mqtt
  name: "temp_out"
  state_topic: "tele/sonoff_95B510/SENSOR"
  #value_template:"{{ value_json.DS18B20.Temperature }}" # когда один датчик
  value_template: '{{ value_json["DS18B20-1"]["Temperature"] }}'
  unit_of_measurement: "°C"

- platform: mqtt
  name: "temp_x"
  state_topic: "tele/sonoff_95B510/SENSOR"
  value_template: '{{ value_json["DS18B20-2"]["Temperature"] }}'
  unit_of_measurement: "°C"

- platform: mqtt
  name: "temp_in"
  state_topic: "tele/sonoff_95B510/SENSOR"
  value_template: '{{ value_json["DS18B20-3"]["Temperature"] }}'
  unit_of_measurement: "°C"

- platform: mqtt
  name: "temp_water"
  state_topic: "tele/sonoff_F4BC40/SENSOR"
  value_template: '{{ value_json["DS18B20"]["Temperature"] }}'
  unit_of_measurement: "°C"

