#Weather prediction

- platform: yr
  name: weather_yr
  forecast: 24
  monitored_conditions:
    - symbol
    - temperature
#    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
#    - fog
#    - cloudiness
#    - lowClouds
#    - mediumClouds
#    - highClouds
#    - dewpointTemperature
