- alias: "Home Assistant on start event"
  hide_entity: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.notify_engine
      data_template:
        title: 'HASS:'
        message: "Home Assistant Application is Up and Running !\nVersion: {{ states('sensor.ha_installed_version') }}"
            
    - service: script.sonoff_qry_states
    


- alias: "Database Purge"
  #hide_entity: True
  trigger:
    platform: time
    at: '12:00:00'
  action:
    - service: recorder.purge
      data:
        keep_days: 20
        repack: false
