- alias: "Home Assistant on start event"
  hide_entity: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.sonoff_qry_states
    
    - service: script.notify_engine
      data_template:
        title: 'HASS:'
        message: "Home Assistant Application is Up and Running !\nVersion: {{ states('sensor.ha_installed_version') }}"
