- alias: "Motion alarm"
  hide_entity: False
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_pir
      to: "on"
  condition:
    - entity_id: device_tracker.vlad_nexus 
      state: 'not_home'
  action:
    - service: script.notify_engine
      data_template:
        title: 'Hall PIR:'
        message: "Alarm! Hall motion detected."
