- alias: "Alarm: Low temperature at home"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.temp_in
        - sensor.temp_x
        - sensor.temp1_sauna
        - sensor.temp2_sauna
      below: 4
      for: "00:10:01"
  action:
    - service: script.notify_engine
      data_template:
        title: "The house freezes"
        message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"
    - service: persistent_notification.create
      data_template:
        message: "{{ trigger.to_state.name }} too low for {{ trigger.for }}!"

- alias: "Notification: Sauna heating"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.temp1_sauna
        - sensor.temp2_sauna
      above: 50
  action:
    - service: script.notify_engine
      data_template:
        title: "Сауна нагрета"
        message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"

- alias: "Notification: Early frosts"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.temp_out
      below: 0
      for: "00:10:00"
  action:
    - service: script.notify_engine
      data_template:
        title: "Заморозки"
        message: "На улице заморозки!"

- alias: "Notification: of main switches"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - switch.sw_main
        - switch.sw_sauna
        - switch.sw_floodlight
  action:
    - service: script.notify_engine
      data_template:
        title: 'Switch'
        message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"
      
              
      