- alias: "Notification: of main switches"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - switch.sw_main
        - switch.sw_sauna
        - switch.sw_floodlight
  action:
    - service: script.notify_engine
      data_template:
        title: 'Switch'
        message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"

#          {% if trigger.entity_id == "switch.sw_plug" %} shell_command.living_room
#          {% elif trigger.entity_id == "switch.sonoff_f4bc40" %} shell_command.another_room
#          {% endif %}


# - alias: "Automatic Theme Change"
#   trigger: 
#     - platform: homeassistant 
#       event: start 
#     - platform: state
#       entity_id: switch.sw_main
#   action: 
#     - service: frontend.set_theme
#       data_template: 
#         name: >  
#           {% if is_state('switch.sw_main', 'on') %} 
#             light
#           {% else %} 
#             dark
#           {% endif %}