- alias: "Notification of main switches"
  hide_entity: False
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - switch.sonoff_mainswitch
#        - switch.sonoff_water
        - switch.sonoff_pow
  action:
    - service: script.notify_engine
      data_template:
        title: 'Switch'
        message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"

#          {% if trigger.entity_id == "switch.sonoff_26575d" %} shell_command.living_room
#          {% elif trigger.entity_id == "switch.sonoff_f4bc40" %} shell_command.another_room
#          {% endif %}
