- platform: nmap_tracker
  hosts: 
    - 192.168.2.0/24
    - 192.168.3.0/24
  track_new_devices: no
  home_interval: 25
  # consider_home: 900
  exclude:
    - 192.168.2.1
    - 192.168.2.2
    - 192.168.2.144
    - 192.168.2.120
    - 192.168.3.1
  scan_options: " -sP "
#  scan_options: " --privileged -sP "
