input_boolean:
  alarming:
    initial: off  
    name: Alarming 
    icon: mdi:shield-sun
  enable_alarm:
    initial: on
    name: Enable alarm on motion
    icon: mdi:shield-key

timer:
  period_timer:
    duration: '00:10:00'
  looper_timer:
    duration: '00:00:01'

automation:


- alias: AutoOnOff main switch
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.alarming
  condition: 
    - condition: state
      entity_id: switch.sonoff_mainswitch 
      state: 'off'
  action:
    service_template: >-
      {{ 'switch.turn_on' if trigger.to_state.state == 'on' else 'switch.turn_off' }}
    data_template:
      entity_id: switch.sonoff_mainswitch


- alias: "Alarm: Motion at home"
  hide_entity: false
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_pir
      to: "on"
  condition: 
    - condition: state
      entity_id: device_tracker.vlad_nexus 
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.enable_alarm 
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alarming
    - service: script.notify_engine
      data_template:
        title: 'Security:'
        message: "Alarm started! Hall motion detected."
    - service: timer.start
      entity_id: timer.period_timer

- alias: Timed auto end of alarm
  hide_entity: true
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.period_timer
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarming
    - service: script.notify_engine
      data_template:
        title: 'Security:'
        message: "Alarm stoped."


- alias: Control alarm loop
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.alarming
  action:
    service_template: >-
      {{ 'timer.start' if trigger.to_state.state == 'on' else 'timer.finish' }}
    data_template:
      entity_id: timer.looper_timer
      duration: "{{ 1 if trigger.to_state.state == 'on' else 0 }}"


- alias: 'Looper service'
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.looper_timer
  action:
    - service: light.toggle
      entity_id: group.alarm_lights


- alias: 'Looper timer finished'
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.looper_timer
  condition:
    condition: state
    entity_id: input_boolean.alarming
    state: 'on'
  action:
  - service: timer.start
    entity_id: timer.looper_timer


group:
  alarm:
    entities:
      - input_boolean.enable_alarm
      - automation.alarm_motion_at_home
      - input_boolean.alarming

homeassistant:
  customize:
    group.alarm:
      friendly_name: 'Security'
 