automation:

- alias: "Alarm: Motion at home"
  hide_entity: False
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_pir
      to: "on"
  condition: 
    - condition: state
      entity_id: device_tracker.vlad_nexus 
      state: 'not_home'
  action:
    - service: script.notify_engine
      data_template:
        title: 'Hall PIR:'
        message: "Alarm! Hall motion detected."
    
    - service: script.turn_on
      entity_id: script.start_flash_alarm
    - service: timer.start
      entity_id: timer.hallway



- alias: Turn off alarm lights
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.hallway
  action:
    - service: script.turn_on
      entity_id: script.stop_flash_alarm



script:

  test_flash:
    alias: Test flash lights
    sequence:
      - service: light.turn_on
        entity_id:
          - light.hall
        data:
          flash: short
  
  start_flash_alarm:
    alias: Start flashing lights
    sequence:
      - service: light.turn_on
        data:
          entity_id: group.alarm_lights
          flash: long

  stop_flash_alarm:
    alias: Stop flashing lights
    sequence:
      - service: light.turn_off
        entity_id: group.alarm_lights



timer:
  hallway:
    duration: '00:10:00'