input_boolean:
  alarming:
    initial: off  
    name: Alarming 
    icon: mdi:shield-sun
  enable_alarm:
    initial: on
    name: Enable alarm on motion
    icon: mdi:shield-key

timer:
  period_timer:
    duration: '00:10:00'
  looper_timer:
    duration: '00:00:01'




automation:

# Включение элобеспечения, если все выключено
- alias: AutoOnOff MAIN switch
  trigger:
    platform: state
    entity_id: input_boolean.alarming
  condition: 
    - condition: state
      entity_id: switch.sw_main 
      state: 'off'
  action:
    service: >-
      {{ 'switch.turn_on' if trigger.to_state.state == 'on' else 'switch.turn_off' }}
    data_template:
      entity_id: switch.sw_main

# Тригер включения сигнализации по движению в доме
- alias: "Alarm: Motion at home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.hall_pir
        # - binary_sensor.ewelink_ms01_80d3901f_ias_zone
      from: "off"
      to: "on"
  condition: 
    - condition: state
      entity_id: input_boolean.enable_alarm 
      state: 'on'
    - condition: state
      entity_id: group.family 
      state: 'not_home'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alarming
    - service: script.notify_engine
      data_template:
        title: 'Security:'
        message: "Alarm started! Hall motion detected."
    - service: timer.start
      entity_id: timer.period_timer

# автомат выключения сигнализации по таймеру
- alias: Timed auto end of alarm
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.period_timer
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarming
    - service: script.notify_engine
      data_template:
        title: 'Security:'
        message: "Alarm stoped."


- alias: Control alarm loop
  trigger:
    platform: state
    entity_id: input_boolean.alarming
  action:
    service: >-
      {{ 'timer.start' if trigger.to_state.state == 'on' else 'timer.finish' }}
    data_template:
      entity_id: timer.looper_timer
      # duration: >-
      #   '{{ 1 if trigger.to_state.state == 'on' else 0 }}'


- alias: 'Looper service'
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.looper_timer
  action:
    - service: light.toggle
      entity_id: group.alarm_lights


- alias: 'Looper timer finished'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.looper_timer
  condition:
    condition: state
    entity_id: input_boolean.alarming
    state: 'on'
  action:
  - service: timer.start
    entity_id: timer.looper_timer

group:
  alarm_lights:
    entities:
      - light.father
      - light.mather
      - light.hall
      # - light.toilet
      - light.floodlight
      - light.sauna
