
apcupsd:
  # host: 192.168.2.144

binary_sensor:
  - platform: apcupsd

sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - maxlinev
      - minlinev
      - outputv



##############################################################################
###  Automations 
##############################################################################
automation:
  - alias: "UPS status notification"
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.ups_online_status
    # condition: 
    #   - condition: state
    #     entity_id: group.family
    #     state: 'not_home'
    action:
      - service: persistent_notification.create
        data:
          title: "UPS:"
          message: "UPS status changed"
          notification_id: "Warning"
      - service: script.notify_engine
        data_template:
          title: 'UPS'
          message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"

