
apcupsd:
  # host: 192.168.2.144

binary_sensor:
  - platform: apcupsd

sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - maxlinev
      - minlinev
      - outputv