
apcupsd:
  # host: 192.168.2.144

binary_sensor:
  - platform: apcupsd

sensor:
  - platform: apcupsd
    resources:
      - bcharge
      # - linev
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      # - maxlinev
      # - minlinev
      # - outputv



##############################################################################
###  Automations 
##############################################################################
automation:
  - alias: "Notification: UPS online"
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.ups_online_status
    action:
      - service: script.notify_engine
        data_template:
          title: 'UPS'
          message: " {{ trigger.to_state.attributes.friendly_name }} -> {{ states(trigger.entity_id) }}"
      # - service: persistent_notification.create
      #   data:
      #     title: "UPS:"
      #     message: "UPS status changed"
      #     notification_id: "Warning"

  - alias: "Notification: UPS battery"
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id: sensor.ups_battery
        below: 20
    action:
      - service: script.notify_engine
        data_template:
          title: 'UPS:'
          message: "UPS battery low! {{ states.sensor.ups_battery.state }}%"
      # - service: persistent_notification.create
      #   data:
      #     title: 'UPS:'
      #     message: "UPS battery low! {{ states.sensor.ups_battery.state }}%"
      #     notification_id: "Critical Alert"
