#sonoff-bridge -------------------------------------
sensor:
  - platform: mqtt
    name: "ha_bridge_rf wifi"
    state_topic: "tele/ha_bridge_rf/STATE"
    value_template: "{{ value_json.Wifi.RSSI }}"
    unit_of_measurement: "%"
    expire_after: 200
  - platform: mqtt
    name: "ha_bridge_rf uptime"
    state_topic: "tele/ha_bridge_rf/STATE"
    value_template: "{{ value_json.Uptime }}"
    unit_of_measurement: ""
    expire_after: 200

    # RF Bridge as sensor - "Data" is the truncated (unique) hex address of the transmitter
  - platform: mqtt
    name: "ha_bridge_rf"
    state_topic: 'tele/ha_bridge_rf/RESULT'
    value_template: "{{ value_json.RfReceived.Data }}"
    expire_after: 15
    icon: mdi:remote

binary_sensor:
  - platform: mqtt
    name: "ha_bridge_rf LWT"
    state_topic: "tele/ha_bridge_rf/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/ha_bridge_rf/STATE"

