#-------------------------------------------
sensor:
  # - platform: version
  #   name: HA Installed Version
  #   scan_interval: 86400
    
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: processor_use
      - type: memory_free
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /home
      # !!! not valid on docker
      # - type: disk_use_percent
      #   arg: /root

  # - platform: time_date
  #   display_options:
  #       - 'time'
  #       - 'date'

##############################################################################
###  Automations - Detect when things are not right. Like any Good Watchdog.
##############################################################################
automation:

  - alias: "Disk Use Alarm"
    trigger:
      - platform: numeric_state
        entity_id: sensor.disk_use_percent_home
        above: 80
    action:
#      - service: script.notify_engine
#        data_template:
#          title: 'Hard Drive Monitor:'
#          message: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_percent_home.state }}%!"

      - service: persistent_notification.create
        data:
          title: "Hard Drive Monitor:"
          message: "Your harddrive is running out of Space! /home:{{ states.sensor.disk_use_percent_home.state }}%!"
          notification_id: "Critical Alert"





shell_command:
  update_config_from_git: 'cd /config && git pull'

script:
  git_pull_config:
    alias: Git pull config & Restart
    sequence:
      - service: shell_command.update_config_from_git
      - service: homeassistant.restart 

