#PIR -------------------------------------

binary_sensor:
  - platform: template
    sensors:
      hall_pir:
        value_template: '{{ is_state("sensor.sonoff_bridge_433", "E7EDEE") }}'
        delay_off: '00:00:15'
        device_class: motion
        friendly_name: "Hall PIR"


sensor:
  - platform: template
    sensors:
      hall_pir_last_changed:
        # value_template: '{{ as_timestamp(states.binary_sensor.hall_pir.last_changed) | timestamp_local }}'
        value_template: '{{ states.binary_sensor.hall_pir.last_changed | timestamp_local }}'
        # device_class: timestamp
        friendly_name: "PIR Last Motion"


##############################################################################
###  Automations 
##############################################################################
automation:
  - alias: "PIR persistent notification"
    initial_state: off
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_pir
        to: "off"
    action:
      - service: persistent_notification.create
        data:
          title: "PIR:"
          message: "Motion detected"
          notification_id: "Warning"
