#PIR -------------------------------------

binary_sensor:
  - platform: template
    sensors:
      hall_pir:
        value_template: '{{ is_state("sensor.sonoff_bridge_433", "E7EDEE") }}'
        delay_off: '00:00:15'
        device_class: motion
        friendly_name: "Hall PIR"


sensor:
  - platform: template
    sensors:
      hall_pir_last_changed:
        value_template: >-
          {% if is_state("sensor.sonoff_bridge_433", "E7EDEE") %}
            {{ as_timestamp(now()) }}
          {% endif %}
        friendly_name: "PIR Last Motion"


group:
  motion_detection:
    entities:
      - binary_sensor.hall_pir
      - sensor.hall_pir_last_changed
        

homeassistant:
  customize:
    #binary_sensor.hall_pir:
      #friendly_name: 'Детектор'
      #icon: mdi:paw
    group.motion_detection:
      friendly_name: 'Движение/Присутствие'


##############################################################################
###  Automations 
##############################################################################
automation:
  - alias: "PIR persistent notification"
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_pir
        to: "off"
    action:
      - service: persistent_notification.create
        data:
          title: "PIR:"
          message: "Motion detected"
          notification_id: "Warning"
