#sonoff-bridge -------------------------------------
sensor:
  - platform: mqtt
    name: "sonoff_B2DF94 wifi"
    state_topic: "tele/sonoff_B2DF94/STATE"
    value_template: "{{ value_json.Wifi.RSSI }}"
    unit_of_measurement: "%"
    expire_after: 200
  - platform: mqtt
    name: "sonoff_B2DF94 uptime"
    state_topic: "tele/sonoff_B2DF94/STATE"
    value_template: "{{ value_json.Uptime }}"
    unit_of_measurement: ""
    expire_after: 200

    # RF Bridge as sensor - "Data" is the truncated (unique) hex address of the transmitter
  - platform: mqtt
    name: "sonoff_bridge_433"
    state_topic: 'tele/sonoff_B2DF94/RESULT'
    value_template: "{{ value_json.RfReceived.Data }}"
    expire_after: 10
    icon: mdi:remote


binary_sensor:
  - platform: mqtt
    name: "sonoff_B2DF94 LWT"
    state_topic: "tele/sonoff_B2DF94/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

group:
  sonoff_bridge:
    entities:
        - sensor.sonoff_bridge_433
        - sensor.sonoff_B2DF94_wifi
        - sensor.sonoff_B2DF94_uptime
        #- binary_sensor.sonoff_B2DF94_lwt


homeassistant:
  customize:
    sensor.sonoff_bridge_433:
      friendly_name: 'Last cod'
    group.sonoff_bridge:
      friendly_name: 'Шлюз RF433'
        

