#sonoff-mainswitch -------------------------------------
switch:
  - platform: mqtt
    name: "sonoff_mainswitch"
    state_topic: "stat/sonoff_95B510/POWER"
    command_topic: "cmnd/sonoff_95B510/POWER"
    availability_topic: "tele/sonoff_95B510/LWT"
#    json_attributes_topic: "tele/sonoff_95B510/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sonoff_mainswitch_timers"
    state_topic: "stat/sonoff_95B510/TIMERS"
    command_topic: "cmnd/sonoff_95B510/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sonoff_95B510/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "mqtt_net_datetime_control"
    state_topic: "tele/sonoff_95B510/STATE"
    value_template: "{{ value_json.Time }}"
    unit_of_measurement: ""
    icon: mdi:timer

  - platform: mqtt
    name: "temp_out"
    state_topic: "tele/sonoff_95B510/SENSOR"
    #value_template:"{{ value_json.DS18B20.Temperature }}" # когда один датчик
    value_template: '{{ value_json["DS18B20-1"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  - platform: mqtt
    name: "temp_in"
    state_topic: "tele/sonoff_95B510/SENSOR"
    value_template: '{{ value_json["DS18B20-2"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  - platform: mqtt
    name: "temp_x"
    state_topic: "tele/sonoff_95B510/SENSOR"
    value_template: '{{ value_json["DS18B20-3"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer

binary_sensor:
  - platform: mqtt
    name: "sonoff_95B510 LWT"
    state_topic: "tele/sonoff_95B510/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sonoff_95B510/STATE"

#input_number:
#  sonoff_mainswitch_slider:
#    name: dT Interval
#    initial: 6
#    min: 0
#    max: 6
#    step: 0.5


