#sonoff-pow -------------------------------------
switch:
  - platform: mqtt
    name: "sonoff_pow"
    state_topic: "stat/sonoff_26575D/POWER"
    command_topic: "cmnd/sonoff_26575D/POWER"
    availability_topic: "tele/sonoff_26575D/LWT"
#    json_attributes_topic: "tele/sonoff_26575D/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
#    retain: false
  - platform: mqtt
    name: "sonoff_pow_timers"
    state_topic: "stat/sonoff_26575D/TIMERS"
    command_topic: "cmnd/sonoff_26575D/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sonoff_26575D/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "sonoff_pow today"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sonoff_pow total"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sonoff_pow power"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "sonoff_pow voltage"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"

binary_sensor:
  - platform: mqtt
    name: "sonoff_26575D LWT"
    state_topic: "tele/sonoff_26575D/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sonoff_26575D/STATE"


