#sonoff-bridge -------------------------------------
sensor:
  - platform: mqtt
    name: "sonoff_B2DF94 wifi"
    state_topic: "tele/sonoff_B2DF94/STATE"
    value_template: "{{ value_json.Wifi.RSSI }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: "sonoff_B2DF94 uptime"
    state_topic: "tele/sonoff_B2DF94/STATE"
    value_template: "{{ value_json.Uptime }}"
    unit_of_measurement: ""

binary_sensor:
  - platform: mqtt
    name: "sonoff_B2DF94 LWT"
    state_topic: "tele/sonoff_B2DF94/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

group:
  sonoff_bridge:
    entities:
        - sensor.sonoff_B2DF94_wifi
        - sensor.sonoff_B2DF94_uptime
        #- binary_sensor.sonoff_B2DF94_lwt


homeassistant:
  customize:
    group.sonoff_bridge:
      friendly_name: 'Шлюз 433'

