#sonoff-water -------------------------------------
switch:
  - platform: mqtt
    name: "sonoff_water"
    state_topic: "stat/sonoff_F4BC40/POWER"
    command_topic: "cmnd/sonoff_F4BC40/POWER"
    availability_topic: "tele/sonoff_F4BC40/LWT"
#    json_attributes_topic: "tele/sonoff_F4BC40/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sonoff_water_timers"
    state_topic: "stat/sonoff_F4BC40/TIMERS"
    command_topic: "cmnd/sonoff_F4BC40/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sonoff_F4BC40/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "temp_water"
    state_topic: "tele/sonoff_F4BC40/SENSOR"
    value_template: '{{ value_json["DS18B20"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer

binary_sensor:
  - platform: mqtt
    name: "sonoff_F4BC40 LWT"
    state_topic: "tele/sonoff_F4BC40/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sonoff_F4BC40/STATE"


##############################################################################
###  Automations 
##############################################################################
automation:
    
  - alias: Automatic winter heating the water pipe
    hide_entity: False
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: sensor.temp_water
    action:
      - condition: template
        value_template: "{{ states('sensor.temp_water') | float != 10 }}"
      - service_template: >-
            {% if states("sensor.temp_water") | float < 5 %}
            switch.turn_on
            {% elif states("sensor.temp_water") | float > 12 %}
            switch.turn_off
            {% endif %}
        entity_id: switch.sonoff_water
        
      
      
      
      
      
