#sonoff-plug -------------------------------------
switch:
  - platform: mqtt
    name: "sonoff_plug"
    state_topic: "stat/sonoff_68B5C7/POWER"
    command_topic: "cmnd/sonoff_68B5C7/POWER"
    availability_topic: "tele/sonoff_68B5C7/LWT"
#    json_attributes_topic: "tele/sonoff_68B5C7/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sonoff_plug_timers"
    state_topic: "stat/sonoff_68B5C7/TIMERS"
    command_topic: "cmnd/sonoff_68B5C7/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sonoff_68B5C7/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
#sensor:

binary_sensor:
  - platform: mqtt
    name: "sonoff_68B5C7 LWT"
    state_topic: "tele/sonoff_68B5C7/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sonoff_68B5C7/STATE"

group:
  sonoff_plug:
    entities:
        - switch.sonoff_plug
        - switch.sonoff_plug_timers

homeassistant:
  customize:
    switch.sonoff_plug:
      icon: mdi:power-plug
      friendly_name: 'Розетка'
    switch.sonoff_plug_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_plug:
      friendly_name: 'Умная розетка'

      
      
      
      
