#sonoff-4pro -------------------------------------

switch:
  - platform: mqtt
    name: "sonoff_801E75 ch1"
    state_topic: "stat/sonoff_801E75/POWER1"
    command_topic: "cmnd/sonoff_801E75/POWER1"
    availability_topic: "tele/sonoff_801E75/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "sonoff_801E75 ch2"
    state_topic: "stat/sonoff_801E75/POWER2"
    command_topic: "cmnd/sonoff_801E75/POWER2"
    availability_topic: "tele/sonoff_801E75/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "sonoff_801E75 ch3"
    state_topic: "stat/sonoff_801E75/POWER3"
    command_topic: "cmnd/sonoff_801E75/POWER3"
    availability_topic: "tele/sonoff_801E75/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "sonoff_801E75 ch4"
    state_topic: "stat/sonoff_801E75/POWER4"
    command_topic: "cmnd/sonoff_801E75/POWER4"
    availability_topic: "tele/sonoff_801E75/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
    
  - platform: mqtt
    name: "sonoff_801E75_timers"
    state_topic: "stat/sonoff_801E75/TIMERS"
    command_topic: "cmnd/sonoff_801E75/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sonoff_801E75/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false  
    
#sensor:
        
binary_sensor:
  - platform: mqtt
    name: "sonoff_801E75 LWT"
    state_topic: "tele/sonoff_801E75/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sonoff_801E75/STATE"


light:
  - platform: switch
    name: Toilet
    entity_id: switch.sonoff_801e75_ch1
  - platform: switch
    name: Father
    entity_id: switch.sonoff_801e75_ch2
  - platform: switch
    name: Mather
    entity_id: switch.sonoff_801e75_ch3
  - platform: switch
    name: Hall
    entity_id: switch.sonoff_801e75_ch4

group:
  sonoff_4pro:
    entities:
      - switch.sonoff_801e75_ch1
      - switch.sonoff_801e75_ch2
      - switch.sonoff_801e75_ch3
      - switch.sonoff_801e75_ch4
      - switch.sonoff_801e75_timers
      #- binary_sensor.sonoff_801e75_lwt


homeassistant:
  customize:
    switch.sonoff_801e75_ch1:
      friendly_name: 'Туалет'
      icon: mdi:lamp
    switch.sonoff_801e75_ch2:
      friendly_name: 'Мама'
      icon: mdi:lamp
    switch.sonoff_801e75_ch3:
      friendly_name: 'Папа'
      icon: mdi:white-balance-incandescent
    switch.sonoff_801e75_ch4:
      friendly_name: 'Зал'
      icon: mdi:white-balance-iridescent
    switch.sonoff_801e75_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
    group.sonoff_4pro:
      friendly_name: 'Свет/Выключатели'

