#sonoff-mainswitch -------------------------------------
switch:
  - platform: mqtt
    name: "sonoff_mainswitch"
    state_topic: "stat/sonoff_95B510/POWER"
    command_topic: "cmnd/sonoff_95B510/POWER"
    availability_topic: "tele/sonoff_95B510/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sonoff_mainswitch_timers"
    state_topic: "stat/sonoff_95B510/TIMERS"
    command_topic: "cmnd/sonoff_95B510/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sonoff_95B510/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "sonoff 95B510 wifi"
    state_topic: "tele/sonoff_95B510/STATE"
    value_template: "{{ value_json.Wifi.RSSI }}"
    unit_of_measurement: "%"
    expire_after: 200
  - platform: mqtt
    name: "sonoff 95B510 uptime"
    state_topic: "tele/sonoff_95B510/STATE"
    value_template: "{{ value_json.Uptime }}"
    unit_of_measurement: ""
    expire_after: 200

  - platform: mqtt
    name: "mqtt_net_datetime_control"
    state_topic: "tele/sonoff_95B510/STATE"
    value_template: "{{ value_json.Time }}"
    unit_of_measurement: ""
    icon: mdi:timer
    json_attributes_topic: "tele/sonoff_95B510/STATE"

  - platform: mqtt
    name: "temp_out"
    state_topic: "tele/sonoff_95B510/SENSOR"
    #value_template:"{{ value_json.DS18B20.Temperature }}" # когда один датчик
    value_template: '{{ value_json["DS18B20-1"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  - platform: mqtt
    name: "temp_in"
    state_topic: "tele/sonoff_95B510/SENSOR"
    value_template: '{{ value_json["DS18B20-2"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  - platform: mqtt
    name: "temp_x"
    state_topic: "tele/sonoff_95B510/SENSOR"
    value_template: '{{ value_json["DS18B20-3"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer

binary_sensor:
  - platform: mqtt
    name: "sonoff_95B510 LWT"
    state_topic: "tele/sonoff_95B510/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
#  - platform: mqtt
#    name: "sonoff_mainswitch_timers"
#    state_topic: "stat/sonoff_95B510/TIMERS"
#    value_template: "{{ value_json.Timers }}"


input_number:
  sonoff_mainswitch_slider:
    name: dT Interval
    initial: 6
    min: 0
    max: 6
    step: 0.5

#script:
#  sonoff_mainswitch_timers_toggle:
#    sequence:
#      - service: mqtt.publish
#        data_template:
#            topic: 'cmnd/sonoff_95B510/TIMERS'
#            payload: "TOGGLE"
#            qos: 2
#            retain: false


group:
  sonoff_mainswitch:
    entities:
        - switch.sonoff_mainswitch
        - sensor.mqtt_net_datetime_control
        - sensor.temp_out
        - sensor.temp_in
        - sensor.temp_x
        - switch.sonoff_mainswitch_timers
#        - binary_sensor.sonoff_mainswitch_timers
#        - script.sonoff_mainswitch_timers_toggle
        - input_number.sonoff_mainswitch_slider
        - sensor.sonoff_95b510_wifi
        - sensor.sonoff_95b510_uptime
        #- binary_sensor.sonoff_95b510_lwt

homeassistant:
  customize:
    switch.sonoff_mainswitch:
      icon: mdi:power
      friendly_name: 'Рубильник'
    sensor.mqtt_net_datetime_control:
      friendly_name: 'Временная метка'
    sensor.temp_out:
      friendly_name: 'Температура снаружи'
    sensor.temp_in:
      friendly_name: 'Температура внутри'
    sensor.temp_x:
      friendly_name: 'Температура в углу'
    switch.sonoff_mainswitch_timers:
      icon: mdi:timer
      friendly_name: 'Таймеры'
      assumed_state: false
    group.sonoff_mainswitch:
      friendly_name: 'Основной выключатель'


