#sonoff-pow -------------------------------------

switch:
  - platform: mqtt
    name: "sonoff_pow"
    state_topic: "stat/sonoff_26575D/POWER"
    command_topic: "cmnd/sonoff_26575D/POWER"
    availability_topic: "tele/sonoff_26575D/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
    
sensor:
  - platform: mqtt
    name: "sonoff 26575D wifi"
    state_topic: "tele/sonoff_26575D/STATE"
    value_template: "{{ value_json.Wifi.RSSI }}"
    unit_of_measurement: "%"
    expire_after: 200
  - platform: mqtt
    name: "sonoff 26575D uptime"
    state_topic: "tele/sonoff_26575D/STATE"
    value_template: "{{ value_json.Uptime }}"
    unit_of_measurement: ""
    expire_after: 200

  - platform: mqtt
    name: "sonoff_pow today"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sonoff_pow total"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sonoff_pow power"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "sonoff_pow voltage"
    state_topic: "tele/sonoff_26575D/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"

binary_sensor:
  - platform: mqtt
    name: "sonoff_26575D LWT"
    state_topic: "tele/sonoff_26575D/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
  - platform: mqtt
    name: "sonoff_26575D_timers"
    state_topic: "stat/sonoff_26575D/TIMERS"
    value_template: "{{ value_json.Timers }}"


group:
  sonoff_pow:
    entities:
        - switch.sonoff_pow
        - sensor.sonoff_pow_voltage
        - sensor.sonoff_pow_power
        - sensor.sonoff_pow_today
        - sensor.sonoff_pow_total
        - binary_sensor.sonoff_26575D_timers
        - sensor.sonoff_26575d_wifi
        - sensor.sonoff_26575d_uptime
        #- binary_sensor.sonoff_26575d_lwt

homeassistant:
  customize:
    sensor.sonoff_pow_power:
      icon: mdi:scale
      friendly_name: 'Мощьность'
    sensor.sonoff_pow_voltage:
      friendly_name: 'Напряжение'
      icon: mdi:flash-circle
    sensor.sonoff_pow_today:
      icon: mdi:chart-timeline
      friendly_name: 'Сегодня'
    sensor.sonoff_pow_total:
      icon: mdi:counter
      friendly_name: 'Всего'
    binary_sensor.sonoff_26575D_timers:
      icon: mdi:flash-circle
      friendly_name: 'Таймеры'
    group.sonoff_pow:
      friendly_name: 'Розетка-счетчик'

