#sonoff-4pro -------------------------------------

switch:
  - platform: mqtt
    name: "sw_4ch_lights ch1"
    state_topic: "stat/sw_4ch_lights/POWER1"
    command_topic: "cmnd/sw_4ch_lights/POWER1"
    availability_topic: "tele/sw_4ch_lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "sw_4ch_lights ch2"
    state_topic: "stat/sw_4ch_lights/POWER2"
    command_topic: "cmnd/sw_4ch_lights/POWER2"
    availability_topic: "tele/sw_4ch_lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "sw_4ch_lights ch3"
    state_topic: "stat/sw_4ch_lights/POWER3"
    command_topic: "cmnd/sw_4ch_lights/POWER3"
    availability_topic: "tele/sw_4ch_lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "sw_4ch_lights ch4"
    state_topic: "stat/sw_4ch_lights/POWER4"
    command_topic: "cmnd/sw_4ch_lights/POWER4"
    availability_topic: "tele/sw_4ch_lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    retain: false
    
  - platform: mqtt
    name: "sw_4ch_lights_timers"
    state_topic: "stat/sw_4ch_lights/RESULT"
    command_topic: "cmnd/sw_4ch_lights/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sw_4ch_lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false  
    
#sensor:
        
binary_sensor:
  - platform: mqtt
    name: "sw_4ch_lights LWT"
    state_topic: "tele/sw_4ch_lights/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sw_4ch_lights/STATE"


light:
  - platform: switch
    name: Toilet
    entity_id: switch.sw_4ch_lights_ch1
  - platform: switch
    name: Mather
    entity_id: switch.sw_4ch_lights_ch2
  - platform: switch
    name: Father
    entity_id: switch.sw_4ch_lights_ch3
  - platform: switch
    name: Hall
    entity_id: switch.sw_4ch_lights_ch4
