#sonoff-mainswitch -------------------------------------
switch:
  - platform: mqtt
    name: "sw_main"
    unique_id: "sw_main"
    state_topic: "stat/sw_main/POWER"
    command_topic: "cmnd/sw_main/POWER"
    availability_topic: "tele/sw_main/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false

  - platform: mqtt
    name: "sw_main_timers"
    state_topic: "stat/sw_main/RESULT"
    command_topic: "cmnd/sw_main/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sw_main/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "mqtt_net_datetime_control"
    state_topic: "tele/sw_main/STATE"
    value_template: "{{ value_json.Time }}"
    unit_of_measurement: ""
    icon: mdi:timer

binary_sensor:
  - platform: mqtt
    name: "sw_main LWT"
    state_topic: "tele/sw_main/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sw_main/STATE"

