#sonoff-plug -------------------------------------
switch:
  - platform: mqtt
    name: "sw_plug2"
    state_topic: "stat/sw_plug2/POWER"
    command_topic: "cmnd/sw_plug2/POWER"
    availability_topic: "tele/sw_plug2/LWT"
#    json_attributes_topic: "tele/sw_plug2/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sw_plug2_timers"
    state_topic: "stat/sw_plug2/TIMERS"
    command_topic: "cmnd/sw_plug2/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sw_plug2/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
#sensor:

binary_sensor:
  - platform: mqtt
    name: "sw_plug2 LWT"
    state_topic: "tele/sw_plug2/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sw_plug2/STATE"

