#sonoff-sauna -------------------------------------
switch:
  - platform: mqtt
    name: "sw_sauna"
    state_topic: "stat/sw_sauna/POWER"
    command_topic: "cmnd/sw_sauna/POWER"
    availability_topic: "tele/sw_sauna/LWT"
#    json_attributes_topic: "tele/sw_sauna/STATE"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sw_sauna_timers"
    state_topic: "stat/sw_sauna/TIMERS"
    command_topic: "cmnd/sw_sauna/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sw_sauna/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "temp1_sauna"
    state_topic: "tele/sw_sauna/SENSOR"
    value_template: '{{ value_json["DS18B20-1"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  - platform: mqtt
    name: "temp2_sauna"
    state_topic: "tele/sw_sauna/SENSOR"
    value_template: '{{ value_json["DS18B20-2"]["Temperature"] }}'
    unit_of_measurement: "°C"
    icon: mdi:thermometer

binary_sensor:
  - platform: mqtt
    name: "sw_sauna LWT"
    state_topic: "tele/sw_sauna/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sw_sauna/STATE"

light:
  - platform: switch
    name: Sauna
    entity_id: switch.sw_sauna

##############################################################################
###  Automations 
##############################################################################
#automation:
#    
#  - alias: Automatic winter heating the sauna pipe
#    initial_state: 'off'
#    trigger:
#      - platform: state
#        entity_id: sensor.temp_sauna
#    action:
#      - condition: template
#        value_template: "{{ states('sensor.temp_sauna') | float != 10 }}"
#      - service_template: >-
#            {% if states("sensor.temp_sauna") | float < 5 %}
#            switch.turn_on
#            {% elif states("sensor.temp_sauna") | float > 12 %}
#            switch.turn_off
#            {% endif %}
#        entity_id: switch.sw_sauna
        
      
      
      
      
      
