#sonoff-sonar -------------------------------------
switch:
  - platform: mqtt
    name: "sw_floodlight"
    state_topic: "stat/sw_floodlight/POWER"
    command_topic: "cmnd/sw_floodlight/POWER"
    availability_topic: "tele/sw_floodlight/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    #retain: false
  - platform: mqtt
    name: "sw_floodlight_timers"
    state_topic: "stat/sw_floodlight/RESULT"
    command_topic: "cmnd/sw_floodlight/TIMERS"
    value_template: "{{ value_json.Timers }}"
    availability_topic: "tele/sw_floodlight/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    
binary_sensor:
  - platform: mqtt
    name: "sw_floodlight LWT"
    state_topic: "tele/sw_floodlight/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity
    json_attributes_topic: "tele/sw_floodlight/STATE"

light:
  - platform: switch
    name: Floodlight
    entity_id: switch.sw_floodlight



