
sensor:
  - platform: yr
    name: weather_yr
    forecast: 24
    monitored_conditions:
        - symbol
        - temperature
        - pressure
        - humidity
        - windSpeed
        - windDirection
    #    - precipitation
    #    - fog
    #    - cloudiness
    #    - lowClouds
    #    - mediumClouds
    #    - highClouds
    #    - dewpointTemperature


