
panel_iframe:
  weather:
    title: Weather
    icon: mdi:weather-pouring
    url: 'https://embed.windy.com/embed2.html?lat=57.868&lon=30.586&zoom=5&level=surface&overlay=gust&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=true&detailLat=59.898&detailLon=30.262&metricWind=default&metricTemp=default&radarRange'



camera:
  - platform: generic
    still_image_url: 'http://www.pogoda.spb.ru/maps/rus_nw_tmp2m_msk_pspb_9.jpg'
    name: "weather radar temp"
  - platform: generic
    still_image_url: 'http://www.pogoda.spb.ru/maps/rus_nw_wind_msk_pspb_9.jpg'
    name: "weather radar wind"
  - platform: generic
    still_image_url: 'http://www.pogoda.spb.ru/maps/rus_nw_press_msk_pspb_24.jpg'
    name: "weather radar press"
  - platform: generic
    still_image_url: 'http://www.pogoda.spb.ru/maps/rus_nw_apcp_msk_pspb_24.jpg'
    name: "weather radar apcp"
    
           

sensor:
  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: "degrees"
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      sunrise:
        value_template: "{{ state_attr('sun.sun', 'next_rising') }}"

  - platform: template
    sensors:
      g61_temperature:
        friendly_name: "met.no Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
      g61_weather:
        friendly_name: "met.no Weather"
        value_template: "{{ states('weather.home') }}"
